
# SEO settings
title: "Hagen"
title2: "Wierstorf" # default: ""
description: "Researcher in all things spatial audio"
keywords: "Hagen Wierstorf, researcher, publications, spatial audio, reproducible research, psychoacoustics"
url: http://hagenw.github.io # site url
baseurl: null # apply null if repo name is something like username.github.io

repo: http://github.com/hagenw/hagenw.github.io

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
#markdown: redcarpet
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Hagen Wierstorf"
  job      : "Post-Doc"
  bio      : "Researcher in all things spatial audio"
  thumb    : /images/author.jpg
  email    : hagenw@posteo.de
  url      : http://hagenw.github.io
  github   : http://github.com/hagenw
  linkedin : http://www.linkedin.com/in/hagen-wierstorf 

# social settings
og_locale: "en_US"

gems:
  - bourbon

# navbar pages
navbar:
  - slug : publications
    title : Publications
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["vendor", "gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
