
# SEO settings
title: "Hagen"
title2: "Wierstorf" # default: ""
description: "Researcher in audio and AI"
keywords: "Hagen Wierstorf, researcher, publications, spatial audio, reproducible research, psychoacoustics, emotion recognition, AI, machine learning"
url: https://hagenw.github.io # site url
baseurl: null # apply null if repo name is something like username.github.io

repo: https://github.com/hagenw/hagenw.github.io

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
#markdown: redcarpet
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Hagen Wierstorf"
  job      : "Researcher"
  bio      : "Researcher in audio and AI"
  thumb    : /images/author.jpg
  email    : hagenw@posteo.de
  url      : https://hagenw.github.io
  github   : https://github.com/hagenw
  linkedin : https://www.linkedin.com/in/hagen-wierstorf

# social settings
og_locale: "en_US"

plugins:
  - bourbon

exclude: ["vendor", "gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
